# Generated by Django 6.0.1 on 2026-02-04 21:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('basemodels', '0004_seed_lessons'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=30)),
                ('lastname', models.CharField(max_length=30)),
                ('birthdate', models.DateField()),
                ('nationalcode', models.CharField(max_length=10, unique=True)),
                ('father_phonenumber', models.CharField(blank=True, max_length=11)),
                ('mother_phonenumber', models.CharField(blank=True, max_length=11)),
                ('home_phonenumber', models.CharField(blank=True, max_length=11)),
                ('classobj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basemodels.classes')),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basemodels.grades')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basemodels.subjects')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, unique=True)),
            ],
        ),
    ]
