# Generated by Django 6.0.1 on 2026-02-07 18:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_alter_student_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2026, 2, 7, 18, 33, 17, 386654, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
