# Generated by Django 6.0.1 on 2026-04-16 19:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('basemodels', '0004_seed_lessons'),
        ('teachers', '0003_alter_teachingassignment_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeeklySchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.CharField(choices=[('saturday', 'Saturday'), ('sunday', 'Sunday'), ('monday', 'Monday'), ('tuesday', 'Tuesday'), ('wednesday', 'Wednesday'), ('thursday', 'Thursday')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('classobj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_schedules', to='basemodels.classes')),
                ('period_1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='weekly_period_1', to='teachers.teachingassignment')),
                ('period_2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='weekly_period_2', to='teachers.teachingassignment')),
                ('period_3', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='weekly_period_3', to='teachers.teachingassignment')),
                ('period_4', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='weekly_period_4', to='teachers.teachingassignment')),
            ],
            options={
                'ordering': ('classobj__name', 'weekday'),
                'constraints': [models.UniqueConstraint(fields=('classobj', 'weekday'), name='uniq_weekly_schedule_per_class_day')],
            },
        ),
    ]
