# Generated by Django 6.0.1 on 2026-04-16 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weeklyschedules', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weeklyschedule',
            name='weekday',
            field=models.CharField(choices=[('saturday', 'شنبه'), ('sunday', 'یکشنبه'), ('monday', 'دوشنبه'), ('tuesday', 'سه\u200cشنبه'), ('wednesday', 'چهارشنبه'), ('thursday', 'پنجشنبه')], max_length=10),
        ),
    ]
