# Generated by Django 6.0.1 on 2026-02-03 22:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basemodels', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lessons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basemodels.grades')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basemodels.subjects')),
            ],
        ),
    ]
