# Generated by Django 6.0.1 on 2026-04-29 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='teachercomment',
            new_name='comments_te_teacher_4b605a_idx',
            old_name='comments_te_teache_2ef671_idx',
        ),
        migrations.RenameIndex(
            model_name='teachercomment',
            new_name='comments_te_student_f5f0c2_idx',
            old_name='comments_te_student_d32658_idx',
        ),
    ]
