# Generated by Django 6.0.1 on 2026-04-24 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scores', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='score',
            options={'ordering': ('-created_at',)},
        ),
        migrations.RemoveField(
            model_name='score',
            name='score_date',
        ),
    ]
