# Generated by Django 6.0.1 on 2026-04-29 18:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('basemodels', '0004_seed_lessons'),
        ('teachers', '0003_alter_teachingassignment_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Homework',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('due_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('classobj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='homeworks', to='basemodels.classes')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='homeworks', to='basemodels.lessons')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='homeworks', to='teachers.teacher')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
