# Generated by Django 6.0.1 on 2026-02-07 18:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('basemodels', '0004_seed_lessons'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=30)),
                ('lastname', models.CharField(max_length=30)),
                ('birthdate', models.DateField()),
                ('nationalcode', models.CharField(max_length=10, unique=True)),
                ('phonenumber', models.CharField(blank=True, max_length=11)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TeachingAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('classobj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basemodels.classes')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basemodels.lessons')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teachers.teacher')),
            ],
        ),
        migrations.AddField(
            model_name='teacher',
            name='teachingassignments',
            field=models.ManyToManyField(blank=True, to='teachers.teachingassignment'),
        ),
    ]
